name: ci

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]
    
env:
  DOTNET_VERSION: "10.0.x"
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: give runner repository files
        uses: actions/checkout@v4
      
      - name: install .net sdk
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
            
      - name: install dependencies
        run: dotnet restore ./AppForDeploy1/AppForDeploy1/AppForDeploy1.csproj
        
      - name: build app
        run: dotnet build ./AppForDeploy1/AppForDeploy1/AppForDeploy1.csproj --no-restore --configuration Release
      
      - name: run unit tests
        run: dotnet test ./AppForDeploy1/AppForDeploy1.Tests/AppForDeploy1.Tests.csproj --no-build --configuration Release --filter Category=Unit --verbosity normal
        
      - name: run test containers
        run: dotnet test ./AppForDeploy1/AppForDeploy1.Tests/AppForDeploy1.Tests.csproj --no-build --configuration Release --filter Category=Integration --verbosity normal

  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: download code into runner
        uses: actions/checkout@v4
      
      - name: log in to ACR
        uses: docker/login-action@v3
        with: 
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./AppForDeploy1/AppForDeploy1
          file: ./AppForDeploy1/AppForDeploy1/Dockerfile
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/appfordeploy1:${{ github.sha }}
            ${{ secrets.ACR_LOGIN_SERVER }}/appfordeploy1:latest

      - name: log in to azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: deploy to container app
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/appfordeploy1:${{ github.sha }}