name: ci

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]
    
env:
  DOTNET_VERSION: "10.0.x"
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: give runner repository files
        uses: actions/checkout@v4
      
      - name: install .net sdk
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
            
      - name: install dependencies
        run: dotnet restore ./AppForDeploy1/AppForDeploy1/AppForDeploy1.csproj
        
      - name: build app
        run: dotnet build ./AppForDeploy1/AppForDeploy1/AppForDeploy1.csproj --no-restore --configuration Release
      
      - name: run unit tests
        run: dotnet test ./AppForDeploy1/AppForDeploy1.Tests/AppForDeploy1.Tests.csproj --no-build --configuration Release --filter Category=Unit --verbosity normal
        
      - name: run test containers
        run: dotnet test ./AppForDeploy1/AppForDeploy1.Tests/AppForDeploy1.Tests.csproj --no-build --configuration Release --filter Category=Integration --verbosity normal
